# Generated by Django 4.2.9 on 2024-01-07 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_user_createdat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="createdAt", new_name="created_at",
        ),
    ]
