# Generated by Django 4.2.9 on 2024-01-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_userbucket_joined_at"),
    ]

    operations = [
        migrations.RenameField(model_name="access", old_name="name", new_name="type",),
    ]
