# Generated by Django 4.2.9 on 2024-01-08 07:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_rename_name_access_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
            ],
            options={"db_table": "field_type",},
        ),
        migrations.CreateModel(
            name="BucketField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=20)),
                ("value", models.CharField(default="", max_length=200)),
                (
                    "created_at",
                    models.DateField(default=datetime.date.today, verbose_name="Date"),
                ),
                (
                    "bucket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.bucket"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="myapp.fieldtype",
                    ),
                ),
            ],
            options={"db_table": "bucket_field",},
        ),
    ]
