# Generated by Django 4.2.9 on 2024-01-08 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_fieldtype_bucketfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bucketfield",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Date"
            ),
        ),
    ]
