# Generated by Django 4.2.9 on 2024-07-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_bucketfield_created_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bucketfield",
            index=models.Index(
                fields=["bucket", "key"], name="bucket_fiel_bucket__840cd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbucket",
            index=models.Index(
                fields=["user", "bucket"], name="user_bucket_user_id_34fab4_idx"
            ),
        ),
    ]
