# Generated by Django 4.2.9 on 2024-07-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_bucketfield_bucket_fiel_bucket__840cd4_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bucket",
            name="is_root",
            field=models.BooleanField(default=True),
        ),
    ]
