# Generated by Django 4.2.9 on 2024-07-23 17:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_bucket_is_root"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArrayField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("value", models.CharField(default="", max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Date"
                    ),
                ),
                (
                    "parent_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.bucketfield",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="myapp.fieldtype",
                    ),
                ),
            ],
            options={
                "db_table": "array_field",
                "indexes": [
                    models.Index(
                        fields=["parent_field", "index"],
                        name="array_field_parent__6e7db3_idx",
                    )
                ],
            },
        ),
    ]
